[package]
name = "xeo"
version = "2.2.2"
edition = "2024"

[dependencies]
clap = { version = ">=4.0", features = ["derive"] }
colored = ">=2.1"
home = ">=0.5"
evalexpr = ">=8.1"
ureq = { version = "2.9", features = ["tls"] }

[profile.release]
opt-level = "z"     # Optimize for size ('s' or 'z')
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce parallel code generation for better optimization
panic = "abort"     # Remove stack unwinding code (saves ~10% size)
strip = true        # Automatically strip symbols (same as running `strip` command)