[build]
rustflags = [
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-s",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-s",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-s",
]
